# Generated by Django 2.1.2 on 2018-11-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField(default=2018, max_length=4)),
                ('movie_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=100)),
                ('shelf_size', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Shelf'),
        ),
    ]
