# Generated by Django 2.1.2 on 2019-03-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_movie_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='.\\collection\\static\\collection\\placeholder_poster.png', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(default=2018),
        ),
    ]
