# Generated by Django 2.1.2 on 2019-03-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20190320_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='\\collection\\static\\collection\\placeholder_poster.png', upload_to='gallery'),
        ),
    ]
