# Generated by Django 2.1.2 on 2019-03-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20190320_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='{% static %} imgs\\placeholder_poster.png', upload_to=''),
        ),
    ]
